controller_list:
  - name: fake_default_controller
    type: $(arg execution_type)
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
initial:  # Define initial robot poses.
  - group: default
    pose: default