controller_list:
  - name: fake_gold_miner_arm_controller
    type: $(arg execution_type)
    joints:
      - base_joint
      - shoulder_joint
      - elbow_joint
      - wrist_joint_1
      - wrist_joint_2
initial:  # Define initial robot poses.
  - group: gold_miner_arm
    pose: default